### ISSUE TITLE
Error while creating project

### ISSUE THREAD

**Issue by kepeder** [avored/pms#3]
Just wanted tried your script, and there is an error with the database setup. I can see that there hasn't been any activity in a while, but just wanted to share this if you should take this up again. I got an error when trying to create a project:
`SQLSTATE[HY000]: General error: 1364 Field 'created_by_user_id' doesn't have a default value (SQL: insert into `projects` (`name`, `description`, `due_date`, `project_status_id`, `project_priority_id`, `assigned_to_user_id`, `updated_at`, `created_at`) values (Test 1, Testing, 2017-10-07, 1, 1, 1, 2017-10-07 16:33:39, 2017-10-07 16:33:39))`.

**Comment by indpurvesh** [comment]
Try now it might work now.
As you have notice this project is on hold for bit long time now.
